#:schema ./schema.json

id = "activepieces"
name = "ActivePieces"
icon = "https://icons.zeabur.com/activepieces.png"
description = "Your friendliest open source all-in-one automation tool"
docs = ""
tags = ["Automation", "Integration"]

[source]
image = "activepieces/activepieces:latest"

[[ports]]
id = "web"
port = 80
type = "TCP"

[[volumes]]
id = "config"
dir = "/root/.activepieces"

[env]
AP_QUEUE_MODE = { default = "MEMORY" }
AP_DB_TYPE = { default = "SQLITE3" }
AP_FRONTEND_URL = { default = "${ZEABUR_WEB_URL}" }
