#:schema ./schema.json

id = "dragonfly"
name = "Dragonfly"
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/database/dragonfly.svg"
description = "Dragonfly is a modern replacement for Redis and Memcached"
tags = ["Database"]

[source]
image = "docker.dragonflydb.io/dragonflydb/dragonfly:v1.13.0"

[[ports]]
id = "database"
port = 6379
type = "TCP"

[[volumes]]
id = "data"
dir = "/data"

[env]
DRAGONFLY_PASSWORD = { default = "${PASSWORD}", expose = true, readonly = true }
DRAGONFLY_ARGS = { default = "--requirepass ${DRAGONFLY_PASSWORD}" }

DRAGONFLY_HOST = { default = "${CONTAINER_HOSTNAME}", expose = true, readonly = true }
DRAGONFLY_PORT = { default = "${DATABASE_PORT}", expose = true, readonly = true }

DRAGONFLY_CONNECTION_STRING = { default = "redis://:${DRAGONFLY_PASSWORD}@${DRAGONFLY_HOST}:${DRAGONFLY_PORT}", expose = true, readonly = true }
DRAGONFLY_URI = { default = "${DRAGONFLY_CONNECTION_STRING}", expose = true, readonly = true }

[[instructions]]
type = "TEXT"
title = "Command to connect to your Dragonfly"
content = "redis-cli -h ${PORT_FORWARDED_HOSTNAME} -p ${DATABASE_PORT_FORWARDED_PORT} -a ${DRAGONFLY_PASSWORD}"

[[instructions]]
type = "PASSWORD"
title = "Dragonfly password"
content = "${DRAGONFLY_PASSWORD}"
category = "Credentials"

[[instructions]]
type = "TEXT"
title = "Redis host"
content = "${PORT_FORWARDED_HOSTNAME}"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "Redis port"
content = "${DATABASE_PORT_FORWARDED_PORT}"
category = "Hostname & Port"
