#:schema ./schema.json

name = "meilisearch"
description = "Meilisearch is a RESTful search API. It aims to be a ready-to-go solution for everyone who wants a fast and relevant search experience for their end-users ⚡️🔎"
icon = "https://www.meilisearch.com/favicon.svg"

[source]
image = "getmeili/meilisearch"

[[volumes]]
id = "data"
dir = "/meili_data"

[env]
MEILI_MASTER_KEY = { default = "${PASSWORD}", expose = true }

[[ports]]
id = "web"
port = 7700
type = "HTTP"

[[instructions]]
type = "PASSWORD"
title = "Meilisearch Master Key"
content = "${MEILI_MASTER_KEY}"
category = "Credentials"
