#:schema ./schema.json

id = "nextcloud"
name = "Nextcloud"
icon = "https://cdn.icon-icons.com/icons2/2699/PNG/512/nextcloud_logo_icon_168948.png"
description = "Nextcloud is a suite of client-server software for creating and using file hosting services."

[source]
image = "nextcloud:26"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[volumes]]
id = "data"
dir = "/var/www/html/"
