#:schema ./schema.json

id = "supabase-realtime"
name = "Supabase Realtime"
description = "Supabase Realtime"
icon = "https://icons.zeabur.com/supabase.png"

[source]
image = "supabase/realtime:v2.25.66"

[[ports]]
id = "web"
port = 4000
type = "HTTP"

[env]
FLY_ALLOC_ID = { default = "fly123" }
DB_NAME = { default = "postgres" }
DNS_NODES = { default = "" }
DB_USER = { default = "postgres" }
API_JWT_SECRET = { default = "${JWT_SECRET}" }
FLY_APP_NAME = { default = "realtime" }
DB_AFTER_CONNECT_QUERY = { default = "SET search_path TO _realtime" }
PORT = { default = "4000" }
SECRET_KEY_BASE = { default = "UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq" }
DB_PORT = { default = "5432" }
DB_HOST = { default = "supabase-postgres.zeabur.internal" }
DB_PASSWORD = { default = "${POSTGRES_PASSWORD}" }
ERL_AFLAGS = { default = "-proto_dist inet_tcp" }
DB_ENC_KEY = { default = "supabaserealtime" }
ENABLE_TAILSCALE = { default = "false" }
